// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | HeroSlice
  | ServicesSlice
  | CtaSlice
  | CaseStudiesSlice
  | WorkingProcessSlice
  | TeamSlice
  | TestimonialsSlice
  | ContactSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page title for SEO
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page description for SEO
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *CaseStudies → Primary → Items*
 */
export interface CaseStudiesSliceDefaultItem {
  /**
   * Case Description field in *CaseStudies → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter case study description
   * - **API ID Path**: case_studies.primary.items[].case_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  case_description: prismic.KeyTextField;
}

/**
 * Primary content in *CaseStudies → Primary*
 */
export interface CaseStudiesSliceDefaultPrimary {
  /**
   * Heading field in *CaseStudies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Case Studies
   * - **API ID Path**: case_studies.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *CaseStudies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: case_studies.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for CaseStudies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudiesSliceDefaultPrimary>,
  Simplify<CaseStudiesSliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudies*
 */
type CaseStudiesSliceVariation = CaseStudiesSliceDefault;

/**
 * CaseStudies Shared Slice
 *
 * - **API ID**: `case_studies`
 * - **Description**: Case studies section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudiesSlice = prismic.SharedSlice<
  "case_studies",
  CaseStudiesSliceVariation
>;

/**
 * Primary content in *Contact → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Heading field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Us
   * - **API ID Path**: contact.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Contact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: contact.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Contact Image field in *Contact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.primary.contact_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  contact_image: prismic.ImageField<never>;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact form section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Cta → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Heading field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter CTA heading
   * - **API ID Path**: cta.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter CTA description
   * - **API ID Path**: cta.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *Cta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text
   * - **API ID Path**: cta.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * CTA Image field in *Cta → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.primary.cta_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_image: prismic.ImageField<never>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Call to action section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Hero → Primary → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Client Logo field in *Hero → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter main heading
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text
   * - **API ID Path**: hero.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Hero Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with heading, description, CTA, and client logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Services → Primary → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Title Line 1 field in *Services → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: First line of service title
   * - **API ID Path**: services.primary.items[].title_line_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_1: prismic.KeyTextField;

  /**
   * Title Line 2 field in *Services → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Second line of service title
   * - **API ID Path**: services.primary.items[].title_line_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_2: prismic.KeyTextField;

  /**
   * Service Image field in *Services → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.items[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Background Color field in *Services → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: bg-gray-light, bg-primary, or bg-dark
   * - **API ID Path**: services.primary.items[].background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;

  /**
   * Text Color field in *Services → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: text-dark or text-white
   * - **API ID Path**: services.primary.items[].text_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_color: prismic.KeyTextField;

  /**
   * Title Background Color field in *Services → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: bg-primary or bg-white
   * - **API ID Path**: services.primary.items[].title_background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_background_color: prismic.KeyTextField;
}

/**
 * Primary content in *Services → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Heading field in *Services → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Services
   * - **API ID Path**: services.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Services → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter services description
   * - **API ID Path**: services.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services section with service cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Team → Primary → Items*
 */
export interface TeamSliceDefaultItem {
  /**
   * Name field in *Team → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member name
   * - **API ID Path**: team.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Team → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member role
   * - **API ID Path**: team.primary.items[].role
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Experience field in *Team → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member experience
   * - **API ID Path**: team.primary.items[].experience
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience: prismic.KeyTextField;

  /**
   * Avatar field in *Team → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.primary.items[].avatar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;
}

/**
 * Primary content in *Team → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team
   * - **API ID Path**: team.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Team → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: team.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Show Button field in *Team → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: team.primary.show_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_button: prismic.BooleanField;

  /**
   * Button Text field in *Team → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See all team
   * - **API ID Path**: team.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  Simplify<TeamSliceDefaultItem>
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team members section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Testimonials → Primary → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Quote field in *Testimonials → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter testimonial quote
   * - **API ID Path**: testimonials.primary.items[].quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * Author field in *Testimonials → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: testimonials.primary.items[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Position field in *Testimonials → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author position
   * - **API ID Path**: testimonials.primary.items[].position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Testimonials
   * - **API ID Path**: testimonials.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: testimonials.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials carousel section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Item in *WorkingProcess → Primary → Items*
 */
export interface WorkingProcessSliceDefaultItem {
  /**
   * Step Number field in *WorkingProcess → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 01
   * - **API ID Path**: working_process.primary.items[].step_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_number: prismic.KeyTextField;

  /**
   * Step Title field in *WorkingProcess → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter step title
   * - **API ID Path**: working_process.primary.items[].step_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Description field in *WorkingProcess → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter step description
   * - **API ID Path**: working_process.primary.items[].step_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_description: prismic.KeyTextField;
}

/**
 * Primary content in *WorkingProcess → Primary*
 */
export interface WorkingProcessSliceDefaultPrimary {
  /**
   * Heading field in *WorkingProcess → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Working Process
   * - **API ID Path**: working_process.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *WorkingProcess → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: working_process.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for WorkingProcess Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkingProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkingProcessSliceDefaultPrimary>,
  Simplify<WorkingProcessSliceDefaultItem>
>;

/**
 * Slice variation for *WorkingProcess*
 */
type WorkingProcessSliceVariation = WorkingProcessSliceDefault;

/**
 * WorkingProcess Shared Slice
 *
 * - **API ID**: `working_process`
 * - **Description**: Working process section with accordion steps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkingProcessSlice = prismic.SharedSlice<
  "working_process",
  WorkingProcessSliceVariation
>;

declare module "@prismicio/client" {
  interface Content {
    homepage: HomepageDocument;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      CaseStudiesSlice,
      CaseStudiesSliceDefaultItem,
      CaseStudiesSliceDefaultPrimary,
      CaseStudiesSliceDefault,
      CaseStudiesSliceVariation,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceDefault,
      ContactSliceVariation,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceDefault,
      CtaSliceVariation,
      HeroSlice,
      HeroSliceDefaultItem,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      ServicesSlice,
      ServicesSliceDefaultItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefault,
      ServicesSliceVariation,
      TeamSlice,
      TeamSliceDefaultItem,
      TeamSliceDefaultPrimary,
      TeamSliceDefault,
      TeamSliceVariation,
      TestimonialsSlice,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefault,
      TestimonialsSliceVariation,
      WorkingProcessSlice,
      WorkingProcessSliceDefaultItem,
      WorkingProcessSliceDefaultPrimary,
      WorkingProcessSliceDefault,
      WorkingProcessSliceVariation,
    };
  }
}
